### ISSUE TITLE
When running the agent on a remote machine from the Informix database server, the monitoring agent is shown as not running

### ISSUE THREAD

**Issue by nitinmathur123** [informix/informixhq-agent#4] opened 2018-05-08 13:15 UTC
I installed InformixHQ Agent & InformixHQ Server on my Windows PC and also built a small IFX instance. I have managed to start HQ server and agent, with below as agent properties

id=1
target.url=jdbc:informix-sqli://nj3dbifx01dev.dev.otc:1526/sysmaster:user=hist;password=***
repository.url=jdbc:informix-sqli://nj3dbifx01dev.dev.otc:1526/eqs_prod:user=hist;password=***
server.host=nitin-7020.pinksheets.net
target.informixdir C:\IDS_DATA
server.port 8080

I am able to connect to most of my database instances but when I tried to add sensors, I see below:

The monitoring agent is not running. You can configure sensors but they will not be deployed until an agent is connected.

However, when I start the agent, it does connect and starts

C:\IDS_Media>java -jar informixhq-agent.jar agent.properties
[main] INFO com.informix.hq.agent.MetricMonitorApplication - InformixHQ Monitori
ng Agent, version 0.1.0 (build date: 2018-04-19T15:22:41-0500)
[main] INFO com.informix.hq.agent.MetricMonitorApplication - Starting Monitor
[main] INFO com.informix.hq.agent.MetricMonitorApplication - Attempting to conne
ct to target database server
[main] INFO com.zaxxer.hikari.HikariDataSource - pool-target - Starting...
[main] INFO com.zaxxer.hikari.HikariDataSource - pool-target - Start completed.
[main] INFO com.informix.hq.agent.MetricMonitorApplication - Connection successf
ul to romeodb
[main] INFO com.informix.hq.agent.WebSocketManager - Attempting to connect to se
rver at ws://nitin-7020.pinksheets.net:8080/ws/
[Thread-2] INFO com.informix.hq.agent.WebSocketManager - Connected

Please suggest how to check why HQ server is unable to find agent?
regards,
Nitin

**Comment by cristian-t** [comment] 2018-05-08 13:57
The agent will try to pair with an existing Informix server defined in InformixHQ first. If that fails, the agent will try to create an Informix server definition for you. Given your agent configuration, the new definition will appear in the root/top-most group, make sure that hasn't happened.

You can also monitor InformixHQ server's log as the agent connects, to get more information about what is happening. The agent clearly connects.

**Comment by nitinmathur123** [comment] 2018-05-08 18:44
When I check the logs of HQ server, I see that agent connected, but then it gives some error about failing to connect database server (). I dont understand where exactly it is trying to connect.

[qtp21185218-113] INFO com.informix.hq.server.agent.AgentWebSocket - Agent 1 con
nected, from 192.78.139.135
[qtp21185218-114] INFO com.zaxxer.hikari.HikariDataSource - InformixHQ-pool-1 -
Starting...
[qtp21185218-114] ERROR com.zaxxer.hikari.pool.HikariPool - InformixHQ-pool-1 -
Exception during pool initialization.
java.sql.SQLException: Can't load driver java.sql.SQLException: com.informix.asf
.IfxASFException: Attempt to connect to database server () failed.
        at com.informix.util.IfxErrMsg.buildException(IfxErrMsg.java:466)
        at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:435)
        at com.informix.util.IfxErrMsg.getLocSQLException(IfxErrMsg.java:505)
        at com.informix.jdbc.IfxDriver.connect(IfxDriver.java:218)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSourc
e.java:117)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:365)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:194)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:459
)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:533)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:114)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
        at com.informix.hq.server.InformixServerConnectionPoolManager.newConnect
ionPool(InformixServerConnectionPoolManager.java:76)
        at com.informix.hq.server.InformixServerConnectionPoolManager.getConnect
ion(InformixServerConnectionPoolManager.java:86)
        at com.informix.hq.server.agent.AgentManager.createServerForAgent(AgentM
anager.java:89)
        at com.informix.hq.server.agent.AgentWebSocket.handleMessage(AgentWebSoc
ket.java:105)
        at com.informix.hq.server.agent.AgentWebSocket.onWebSocketBinary(AgentWe
bSocket.java:72)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.on
BinaryMessage(JettyListenerEventDriver.java:82)
        at org.eclipse.jetty.websocket.common.message.SimpleBinaryMessage.messag
eComplete(SimpleBinaryMessage.java:68)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendM
essage(AbstractEventDriver.java:66)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.on
BinaryFrame(JettyListenerEventDriver.java:68)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomin
gFrame(AbstractEventDriver.java:157)
        at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(Web
SocketSession.java:367)
        at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incoming
Frame(ExtensionStack.java:220)
        at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220
)
        at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:256)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.rea
dParse(AbstractWebSocketConnection.java:675)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onF
illable(AbstractWebSocketConnection.java:505)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(Abstra
ctConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoin
t.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeP
roduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceC
onsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(Exec
uteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPoo
l.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool
.java:589)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.sql.SQLException: com.informix.asf.IfxASFException: Attempt to c
onnect to database server () failed.
        at com.informix.jdbc.IfxSqliConnect.<init>(IfxSqliConnect.java:1663)
        at com.informix.jdbc.IfxDriver.connect(IfxDriver.java:200)
        ... 32 more
Caused by: com.informix.asf.IfxASFException: Attempt to connect to database serv
er () failed.
        at com.informix.util.IfxErrMsg.getLocIfxASFException(IfxErrMsg.java:763)

        at com.informix.asf.Connection.openSocket(Connection.java:1834)
        at com.informix.asf.Connection.<init>(Connection.java:411)
        at com.informix.jdbc.IfxSqliConnect.<init>(IfxSqliConnect.java:1382)
        ... 33 more
Caused by: java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at com.informix.asf.Connection.getSocket(Connection.java:2180)
        at com.informix.asf.Connection.openSocket(Connection.java:1796)
        ... 35 more
[qtp21185218-114] ERROR com.informix.hq.server.agent.AgentWebSocket - Could not
process message from agent
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initial
ize pool: Can't load driver java.sql.SQLException: com.informix.asf.IfxASFExcept
ion: Attempt to connect to database server () failed.
        at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(Hi
kariPool.java:568)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:554)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:114)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
        at com.informix.hq.server.InformixServerConnectionPoolManager.newConnect
ionPool(InformixServerConnectionPoolManager.java:76)
        at com.informix.hq.server.InformixServerConnectionPoolManager.getConnect
ion(InformixServerConnectionPoolManager.java:86)
        at com.informix.hq.server.agent.AgentManager.createServerForAgent(AgentM
anager.java:89)
        at com.informix.hq.server.agent.AgentWebSocket.handleMessage(AgentWebSoc
ket.java:105)
        at com.informix.hq.server.agent.AgentWebSocket.onWebSocketBinary(AgentWe
bSocket.java:72)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.on
BinaryMessage(JettyListenerEventDriver.java:82)
        at org.eclipse.jetty.websocket.common.message.SimpleBinaryMessage.messag
eComplete(SimpleBinaryMessage.java:68)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendM
essage(AbstractEventDriver.java:66)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.on
BinaryFrame(JettyListenerEventDriver.java:68)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomin
gFrame(AbstractEventDriver.java:157)
        at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(Web
SocketSession.java:367)
        at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incoming
Frame(ExtensionStack.java:220)
        at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220
)
        at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:256)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.rea
dParse(AbstractWebSocketConnection.java:675)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onF
illable(AbstractWebSocketConnection.java:505)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(Abstra
ctConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoin
t.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeP
roduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceC
onsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(Exec
uteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPoo
l.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool
.java:589)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.sql.SQLException: Can't load driver java.sql.SQLException: com.i
nformix.asf.IfxASFException: Attempt to connect to database server () failed.
        at com.informix.util.IfxErrMsg.buildException(IfxErrMsg.java:466)
        at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:435)
        at com.informix.util.IfxErrMsg.getLocSQLException(IfxErrMsg.java:505)
        at com.informix.jdbc.IfxDriver.connect(IfxDriver.java:218)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSourc
e.java:117)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:365)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:194)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:459
)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:533)
        ... 27 more
Caused by: java.sql.SQLException: com.informix.asf.IfxASFException: Attempt to c
onnect to database server () failed.
        at com.informix.jdbc.IfxSqliConnect.<init>(IfxSqliConnect.java:1663)
        at com.informix.jdbc.IfxDriver.connect(IfxDriver.java:200)
        ... 32 more
Caused by: com.informix.asf.IfxASFException: Attempt to connect to database serv
er () failed.
        at com.informix.util.IfxErrMsg.getLocIfxASFException(IfxErrMsg.java:763)

        at com.informix.asf.Connection.openSocket(Connection.java:1834)
        at com.informix.asf.Connection.<init>(Connection.java:411)
        at com.informix.jdbc.IfxSqliConnect.<init>(IfxSqliConnect.java:1382)
        ... 33 more
Caused by: java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at com.informix.asf.Connection.getSocket(Connection.java:2180)
        at com.informix.asf.Connection.openSocket(Connection.java:1796)
        ... 35 more
[qtp21185218-118] INFO com.informix.hq.server.agent.AgentWebSocket - Agent 1 dis
connected

**Comment by ekuehnhausen** [comment] 2018-05-08 18:56
Is your agent running on the same host machine as the Informix database server?

**Comment by nitinmathur123** [comment] 2018-05-08 18:59
I installed HQ server, agent and windows version of IFX on my windows PC (nitin-7020.pinksheets.net). In agent properties file, I have set the target url and repository url as one of our DB instance on LINUX

id=1
target.url=jdbc:informix-sqli://nj3dbifx01dev.dev.otc:1526/sysmaster:user=hist;password=***
repository.url=jdbc:informix-sqli://nj3dbifx01dev.dev.otc:1526/eqs_prod:user=hist;password=***
server.host=nitin-7020.pinksheets.net
target.informixdir C:\IDS_DATA
server.port 8080

**Comment by ekuehnhausen** [comment] 2018-05-08 19:12
We only support running the agent on the same host machine as the target database server (target.url). So you should move the agent to the Linux machine and start it there.

**Comment by Mukesh1328** [comment] 2018-05-15 07:29
While starting the Agentthe error im getting is 
C:\Users\mukesh.b>java -jar D:\informix_soft_bundle\informixHQ\informixhq-agent-0.1.0.jar D:\informix_soft_bundle\informixHQ\monitor.properties
[main] INFO com.informix.hq.agent.MetricMonitorApplication - InformixHQ Monitoring Agent, version 0.1.0 (build date: 2018-04-19T15:22:41-0500)
[main] INFO com.informix.hq.agent.MetricMonitorApplication - Starting Monitor
[main] INFO com.informix.hq.agent.MetricMonitorApplication - Attempting to connect to target database server
[main] INFO com.zaxxer.hikari.HikariDataSource - pool-target - Starting...
[main] ERROR com.zaxxer.hikari.pool.HikariPool - pool-target - Exception during pool initialization.
java.util.NoSuchElementException
        at java.util.StringTokenizer.nextToken(Unknown Source)
        at java.util.StringTokenizer.nextToken(Unknown Source)
        at com.informix.jdbc.IfxDriver.getPropertiesFromUrl(IfxDriver.java:756)
        at com.informix.jdbc.IfxDriver.connect(IfxDriver.java:193)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:365)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:194)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:459)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:533)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:114)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
        at com.informix.hq.agent.InformixConnectionManager.newConnectionPool(InformixConnectionManager.java:77)
        at com.informix.hq.agent.InformixConnectionManager.getTargetConnection(InformixConnectionManager.java:84)
        at com.informix.hq.agent.MetricMonitorApplication.getTargetDBServerName(MetricMonitorApplication.java:168)
        at com.informix.hq.agent.MetricMonitorApplication.run(MetricMonitorApplication.java:134)
        at com.informix.hq.agent.MetricMonitorApplication.main(MetricMonitorApplication.java:80)
[main] ERROR com.informix.hq.agent.MetricMonitorApplication - Unexpected exception
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: null
        at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:568)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:554)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:114)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
        at com.informix.hq.agent.InformixConnectionManager.newConnectionPool(InformixConnectionManager.java:77)
        at com.informix.hq.agent.InformixConnectionManager.getTargetConnection(InformixConnectionManager.java:84)
        at com.informix.hq.agent.MetricMonitorApplication.getTargetDBServerName(MetricMonitorApplication.java:168)
        at com.informix.hq.agent.MetricMonitorApplication.run(MetricMonitorApplication.java:134)
        at com.informix.hq.agent.MetricMonitorApplication.main(MetricMonitorApplication.java:80)
Caused by: java.util.NoSuchElementException
        at java.util.StringTokenizer.nextToken(Unknown Source)
        at java.util.StringTokenizer.nextToken(Unknown Source)
        at com.informix.jdbc.IfxDriver.getPropertiesFromUrl(IfxDriver.java:756)
        at com.informix.jdbc.IfxDriver.connect(IfxDriver.java:193)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:365)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:194)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:459)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:533)
        ... 7 more
[main] INFO com.informix.hq.agent.MetricMonitorApplication - Stopping monitoring
Exception in thread "main" java.lang.NullPointerException
        at com.informix.hq.agent.MetricMonitorApplication.stopMonitoring(MetricMonitorApplication.java:243)
        at com.informix.hq.agent.MetricMonitorApplication.shutdownThreads(MetricMonitorApplication.java:153)
        at com.informix.hq.agent.MetricMonitorApplication.run(MetricMonitorApplication.java:147)
        at com.informix.hq.agent.MetricMonitorApplication.main(MetricMonitorApplication.java:80)




Im running the agent where the database server is running and below it the properties file info for agent


id=1
target.url=jdbc:informix-sqli://199.166.155.74:9088/sysmaster:user=informix;password:admin@1234
target.informixdir=D:\informix_soft_bundle
repository.url=jdbc:informix-sqli://199.166.155.74:9088/sysadmin:user=informix;password:admin@1234
server.host=SRI-PC34.cgsl.com
server.port=8080

**Comment by ekuehnhausen** [comment] 2018-05-15 14:15
@Mukesh1328 in your JDBC URLs, you have **password:**_mypassword_ instead of **password=**_mypassword_

The password keyword needs to be followed by a equals sign, not a colon.

**Comment by ekuehnhausen** [comment] 2018-05-15 14:18
@nitinmathur123 In the next release of InformixHQ, which will be available soon, we'll be adding support for running the agent on a remote machine from the Informix database server. However, in such a configuration, the agent will be limited to only SQL based sensors (i.e. limited to only data it can get through a JDBC connection). 

It will continue to be recommended to run the agent on the same host as the Informix database server so that the full complement of agent functionality is available which includes things like gathering data about OS statistics and monitoring Informix log files.

**Comment by ekuehnhausen** [comment] 2018-06-07 21:39
Fixed in version 0.2.0

**Closed by ekuehnhausen** 2018-06-07 21:39 UTC
Labels: enhancement
