### ISSUE TITLE
Agent Error when Start

### ISSUE THREAD

**Issue by esousaa** [informix/informixhq-agent#9] opened 2018-05-22 15:00 UTC
The following error occurred in server, when I start the agent:

[qtp14570065-9199] INFO com.informix.hq.server.agent.AgentWebSocket - Agent 200 connected, from 10.71.40.27
[qtp14570065-9091] INFO com.zaxxer.hikari.HikariDataSource - InformixHQ-pool-5 - Starting...
[qtp14570065-9091] ERROR com.zaxxer.hikari.pool.HikariPool - InformixHQ-pool-5 - Exception during pool initialization.
java.sql.SQLException: Can't load driver java.sql.SQLException: com.informix.asf.IfxASFException: Attempt to connect to database server () failed.
        at com.informix.util.IfxErrMsg.buildException(IfxErrMsg.java:466)
        at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:435)
        at com.informix.util.IfxErrMsg.getLocSQLException(IfxErrMsg.java:505)
        at com.informix.jdbc.IfxDriver.connect(IfxDriver.java:218)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:365)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:194)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:459)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:533)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:114)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
        at com.informix.hq.server.InformixServerConnectionPoolManager.newConnectionPool(InformixServerConnectionPoolManager.java:76)
        at com.informix.hq.server.InformixServerConnectionPoolManager.getConnection(InformixServerConnectionPoolManager.java:86)
        at com.informix.hq.server.agent.AgentManager.createServerForAgent(AgentManager.java:89)
        at com.informix.hq.server.agent.AgentWebSocket.handleMessage(AgentWebSocket.java:105)
        at com.informix.hq.server.agent.AgentWebSocket.onWebSocketBinary(AgentWebSocket.java:72)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onBinaryMessage(JettyListenerEventDriver.java:82)
        at org.eclipse.jetty.websocket.common.message.SimpleBinaryMessage.messageComplete(SimpleBinaryMessage.java:68)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:66)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onBinaryFrame(JettyListenerEventDriver.java:68)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:157)
        at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:367)
        at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:220)
        at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
        at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:256)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:675)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:505)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.sql.SQLException: com.informix.asf.IfxASFException: Attempt to connect to database server () failed.
        at com.informix.jdbc.IfxSqliConnect.<init>(IfxSqliConnect.java:1663)
        at com.informix.jdbc.IfxDriver.connect(IfxDriver.java:200)
        ... 32 more
Caused by: com.informix.asf.IfxASFException: Attempt to connect to database server () failed.
        at com.informix.util.IfxErrMsg.getLocIfxASFException(IfxErrMsg.java:763)
        at com.informix.asf.Connection.openSocket(Connection.java:1834)
        at com.informix.asf.Connection.<init>(Connection.java:411)
        at com.informix.jdbc.IfxSqliConnect.<init>(IfxSqliConnect.java:1382)
        ... 33 more
Caused by: java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at com.informix.asf.Connection.getSocket(Connection.java:2180)
        at com.informix.asf.Connection.openSocket(Connection.java:1796)
        ... 35 more
[qtp14570065-9091] ERROR com.informix.hq.server.agent.AgentWebSocket - Could not process message from agent
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Can't load driver java.sql.SQLException: com.informix.asf.IfxASFException: Attempt to connect to database server () failed.
        at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:568)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:554)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:114)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
        at com.informix.hq.server.InformixServerConnectionPoolManager.newConnectionPool(InformixServerConnectionPoolManager.java:76)
        at com.informix.hq.server.InformixServerConnectionPoolManager.getConnection(InformixServerConnectionPoolManager.java:86)
        at com.informix.hq.server.agent.AgentManager.createServerForAgent(AgentManager.java:89)
        at com.informix.hq.server.agent.AgentWebSocket.handleMessage(AgentWebSocket.java:105)
        at com.informix.hq.server.agent.AgentWebSocket.onWebSocketBinary(AgentWebSocket.java:72)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onBinaryMessage(JettyListenerEventDriver.java:82)
        at org.eclipse.jetty.websocket.common.message.SimpleBinaryMessage.messageComplete(SimpleBinaryMessage.java:68)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:66)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onBinaryFrame(JettyListenerEventDriver.java:68)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:157)
        at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:367)
        at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:220)
        at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
        at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:256)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:675)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:505)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.sql.SQLException: Can't load driver java.sql.SQLException: com.informix.asf.IfxASFException: Attempt to connect to database server () failed.
        at com.informix.util.IfxErrMsg.buildException(IfxErrMsg.java:466)
        at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:435)
        at com.informix.util.IfxErrMsg.getLocSQLException(IfxErrMsg.java:505)
        at com.informix.jdbc.IfxDriver.connect(IfxDriver.java:218)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:365)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:194)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:459)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:533)
        ... 27 more
Caused by: java.sql.SQLException: com.informix.asf.IfxASFException: Attempt to connect to database server () failed.
        at com.informix.jdbc.IfxSqliConnect.<init>(IfxSqliConnect.java:1663)
        at com.informix.jdbc.IfxDriver.connect(IfxDriver.java:200)
        ... 32 more
Caused by: com.informix.asf.IfxASFException: Attempt to connect to database server () failed.
        at com.informix.util.IfxErrMsg.getLocIfxASFException(IfxErrMsg.java:763)
        at com.informix.asf.Connection.openSocket(Connection.java:1834)
        at com.informix.asf.Connection.<init>(Connection.java:411)
        at com.informix.jdbc.IfxSqliConnect.<init>(IfxSqliConnect.java:1382)
        ... 33 more
Caused by: java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at com.informix.asf.Connection.getSocket(Connection.java:2180)
        at com.informix.asf.Connection.openSocket(Connection.java:1796)
        ... 35 more

**Comment by ekuehnhausen** [comment] 2018-05-22 15:33
It looks like you are not running the agent on the same host machine as your target Informix database server. In version 0.1.0, we only support running the agent on the same host on the database server.

**Comment by ekuehnhausen** [comment] 2018-05-22 15:33
This looks to be a duplicate of #4

**Comment by esousaa** [comment] 2018-05-22 16:41
My agent is in the database server and my InformixHQ-Server is in my desktop, Is there a problem?

**Comment by ekuehnhausen** [comment] 2018-05-22 18:50
You described the correct setup.

Here's what I can tell from the stack trace. The agent successfully connected to the InformixHQ server. The server is trying to match the information about the target database server that is getting from the agent to the database server information that the InformixHQ server already has. The InformixHQ server doesn't have a match for the server information which could happen if you haven't yet added that server in the UI, if the server was added with incorrect host or port information, or if the agent isn't on the same host as the database server. Because it doesn't find a match, the InformixHQ server tries to automatically define that server based on the information it gets from the agent. It will take the hostname from agent's websocket connection, plus the port and user/password information for the target database server that it gets from the agent when it connects. It will try to create a JDBC connection to the database server based on that inforfmation... this database connection is failing. So the InformixHQ server cannot determine what Informix database server that the agent is connected to.

**Comment by ekuehnhausen** [comment] 2018-05-22 18:52
I do have a fix coming in the next release that automatically detect if the agent is local or remote from the database server. This aids the InformixHQ server in these cases when it is trying to connect to the target database just based on agent information alone.

**Comment by ekuehnhausen** [comment] 2018-06-07 21:43
I am going to marked this as fixed. Please try with version 0.2.0 InformixHQ. That will detect and log if the agent is local or remote and does support running in both mode. If you see a further issue on version 0.2.0, open a new issue.

**Closed by ekuehnhausen** 2018-06-07 21:43 UTC
